trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'
  clean: true

steps:
  - task: UseNode@1
    inputs:
      version: '23.x'
      checkLatest: true

  - script: |
      corepack enable
      corepack prepare pnpm@9.15.5 --activate
    displayName: 'Enable Corepack & Setup pnpm'

  - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      restoreKeys: |
        pnpm | "$(Agent.OS)"
      path: ~/.pnpm-store
    displayName: 'Cache pnpm store'

  - script: pnpm install --frozen-lockfile --store ~/.pnpm-store
    displayName: 'Install dependencies'

  - script: pnpm run lint
    displayName: 'Run ESLint'

  - script: pnpm exec tsc --noEmit
    displayName: 'TypeScript type check'

  - script: pnpm run build
    displayName: 'Build the application'
