trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'test'

steps:
  - task: UseNode@1
    inputs:
      version: '23.x'
      checkLatest: true

  - script: |
      corepack enable
      corepack prepare pnpm@9.15.5 --activate
    displayName: 'Enable Corepack & Setup pnpm'

  - script: pnpm install --frozen-lockfile
    displayName: 'Install dependencies'

  - script: pnpm run lint
    displayName: 'Run ESLint'


  - script: pnpm exec tsc --noEmit
    displayName: 'TypeScript type check'

  - script: rm -rf .next
    displayName: 'Remove .next folder'

  - script: pnpm run build
    displayName: 'Build the application'
