trigger:
  branches:
    include:
      - main
      - develop
      - feat-profile-list-item-component

pool:
  vmImage: 'ubuntu-latest'
  clean: true

steps:
  - task: UseNode@1
    inputs:
      version: '23.x'
      checkLatest: true

  - script: |
      corepack enable
      corepack prepare pnpm@9.15.5 --activate
    displayName: 'Enable Corepack & Setup pnpm'

  - script: pnpm install --frozen-lockfile
    displayName: 'Install dependencies'

  - script: |
      npx playwright install --with-deps
    displayName: 'Install Playwright'

  - script: |
      pnpm build-storybook --quiet
    displayName: 'Build Storybook'

  - script: |
      npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
        "npx http-server storybook-static --port 6006 --silent" \
        "npx wait-on tcp:127.0.0.1:6006 && pnpm test-storybook"
    displayName: 'Serve Storybook and run tests'
    timeoutInMinutes: 60
