'use client';
import type { Metadata } from 'next';

import localFont from 'next/font/local';
import './globals.css';
import { AppSidebar } from '@/components/ui/Sidebar/app-sidebar';
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/Sidebar/sidebar';
import { MobileNavigation } from '@/components/ui/MobileNavigation/Mobilenavigation';
import { linkProps } from '@/types/link';
import { StatusSidebar } from '@/components/ui/StatusSidebar/StatusSidebar';
import type * as React from 'react';

import { useState } from 'react';

const monumentGrotesk = localFont({
  src: [
    {
      path: '../public/fonts/monument-grotesk/ABCMonumentGrotesk-Light-Trial.woff2',
      weight: '300',
      style: 'normal',
    },
  ],
  variable: '--font-monument-grotesk',
});

const ibxMono = localFont({
  src: [
    {
      path: '../public/fonts/IBMPlexMono/IBMPlexMono-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/IBMPlexMono/IBMPlexMono-Regular.ttf',
      weight: '350',
      style: 'normal',
    },
  ],
  variable: '--font-ibx-mono', // CSS variable for the font
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [open, setOpen] = useState('navigation');
  const links: Array<linkProps> = [
    { href: '#', label: 'Today' },
    { href: '#', label: 'Contact' },
    { href: '#', label: 'Profile' },
  ];

  return (
    <html lang="en">
      <body className={`${monumentGrotesk.variable} ${ibxMono.variable} font-sans antialiased`}>
        <SidebarProvider
          open={open === 'navigation'}
          onOpenChange={() => setOpen(open === 'navigation' ? 'status' : 'navigation')}
        >
          <AppSidebar className={'md:block hidden'} linkList={links} />
          <SidebarInset className={'relative'}>
            {children}
            <SidebarTrigger
              open={open}
              setOpen={setOpen}
              className="fixed bottom-5 right-3.5 hidden md:block"
            />
          </SidebarInset>
          <StatusSidebar open={open} setOpen={setOpen} />
        </SidebarProvider>

        <MobileNavigation linkList={links} />
      </body>
    </html>
  );
}
