import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { MobileNavigation } from '@/components/ui/MobileNavigation/Mobilenavigation';
import { linkProps } from '@/types/link';
import type * as React from 'react';
import { SidebarProviderWrapper } from '@/components/SidebarProviderWrapper/SidebarProviderWrapper';

const monumentGrotesk = localFont({
  src: [
    {
      path: '../public/fonts/monument-grotesk/ABCMonumentGrotesk-Light-Trial.woff2',
      weight: '300',
      style: 'normal',
    },
  ],
  variable: '--font-monument-grotesk',
});

const ibxMono = localFont({
  src: [
    {
      path: '../public/fonts/IBMPlexMono/IBMPlexMono-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/IBMPlexMono/IBMPlexMono-Regular.ttf',
      weight: '350',
      style: 'normal',
    },
  ],
  variable: '--font-ibx-mono', // CSS variable for the font
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links: Array<linkProps> = [
    { href: '#', label: 'Today' },
    { href: '#', label: 'Contact' },
    { href: '#', label: 'Profile' },
  ];

  return (
    <html lang="en">
      <body className={`${monumentGrotesk.variable} ${ibxMono.variable} font-sans antialiased`}>
        <SidebarProviderWrapper links={links}>{children}</SidebarProviderWrapper>

        <MobileNavigation linkList={links} />
      </body>
    </html>
  );
}
