import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Logo } from '@/components/ui/Logo/Logo';
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarHeader,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/Sidebar/sidebar';
import Link from 'next/link';

const monumentGrotesk = localFont({
  src: [
    {
      path: '../public/fonts/monument-grotesk/ABCMonumentGrotesk-Light-Trial.woff2',
      weight: '300',
      style: 'normal',
    },
  ],
  variable: '--font-monument-grotesk',
});

const ibxMono = localFont({
  src: [
    {
      path: '../public/fonts/IBMPlexMono/IBMPlexMono-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/IBMPlexMono/IBMPlexMono-Regular.ttf',
      weight: '350',
      style: 'normal',
    },
  ],
  variable: '--font-ibx-mono', // CSS variable for the font
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monumentGrotesk.variable} ${ibxMono.variable} font-sans antialiased`}>
        <SidebarProvider>
          <Sidebar>
            <SidebarHeader>
              <Logo />
            </SidebarHeader>

            <SidebarContent className={'mt-auto'}>
              <SidebarGroup>
                <Link href="/">Test</Link>
                <Link href="/">Test</Link>
                <Link href="/">Test</Link>
                <Link href="/">Test</Link>
                <Link href="/">Test</Link>
              </SidebarGroup>
            </SidebarContent>
          </Sidebar>
          <SidebarTrigger />
        </SidebarProvider>
        {children}
      </body>
    </html>
  );
}
